name: CI/CD - Calculator App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python (optional, for linting or other tasks)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Set up Node.js for Playwright
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Playwright & dependencies
      - name: Install Playwright
        run: |
          npm install -g playwright
          playwright install --with-deps

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest .

      # Run pytest inside Docker
      - name: Run pytest in Docker
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest pytest

      # Run Playwright tests (on host machine)
      - name: Run Playwright tests
        run: |
          cd tests/playwright
          npx playwright test

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest
